#数据库连接
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/blog?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: localhost
    port: 6379
    database: 0

comment:
  avatar: static/images/avatar.gif
#日志
logging:
  level:
    root: info
    com.xsyz: debug
  file:
    path: log/blog.log
#端口
server:
  port: 8080
#mybatis
mybatis:
  mapper-locations: com/xsyz/blog/mapper/*.xml
  type-aliases-package: com.xsyz.po
  configuration:
    map-underscore-to-camel-case: true
#分页
pagehelper:
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

